"""Phase 5：生成代码检测、派发合成、多仓库注册表。"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from code_to_skill.code_graph import run_code_graph_pipeline
from code_to_skill.code_graph.callback_synthesis import synthesize_interface_dispatch
from code_to_skill.code_graph.generated_detection import classify_file, is_generated_content
from code_to_skill.code_graph.registry import GraphRegistry, GraphSource
from code_to_skill.code_graph.types import CodeGraph, GraphEdge, EdgeKind, GraphNode, NodeKind


def test_generated_content_marker():
    assert is_generated_content("// @Generated by protoc\npackage x;")
    assert classify_file("src/Foo.java", b"// AUTO-GENERATED\nclass Foo {}") == "generated"


def test_generated_path():
    assert classify_file("src/generated/Foo.java") == "generated"


def test_interface_dispatch_synthesis():
    graph = CodeGraph(
        nodes=[
            GraphNode(id="I.java::Processor", kind=NodeKind.interface, name="Processor", file_path="I.java"),
            GraphNode(id="I.java::process", kind=NodeKind.method, name="process", file_path="I.java"),
            GraphNode(id="Impl.java::StripeProcessor", kind=NodeKind.class_, name="StripeProcessor", file_path="Impl.java"),
            GraphNode(id="Impl.java::process", kind=NodeKind.method, name="process", file_path="Impl.java"),
            GraphNode(id="Svc.java::run", kind=NodeKind.method, name="run", file_path="Svc.java"),
        ],
        edges=[
            GraphEdge(source="Impl.java::StripeProcessor", target="I.java::Processor", kind=EdgeKind.implements),
            GraphEdge(source="I.java::Processor", target="I.java::process", kind=EdgeKind.contains),
            GraphEdge(source="Impl.java::StripeProcessor", target="Impl.java::process", kind=EdgeKind.contains),
            GraphEdge(source="Svc.java::run", target="I.java::process", kind=EdgeKind.calls),
        ],
    )
    synth = synthesize_interface_dispatch(graph)
    assert synth
    targets = {e.target for e in synth}
    assert "Impl.java::process" in targets


@pytest.fixture
def dual_graphs(tmp_path):
    repos = []
    for name in ("alpha", "beta"):
        repo = tmp_path / name
        pkg = repo / "com" / name
        pkg.mkdir(parents=True)
        (pkg / f"{name.capitalize()}Service.java").write_text(
            f"package com.{name};\npublic class {name.capitalize()}Service {{}}\n",
            encoding="utf-8",
        )
        out = tmp_path / "out" / name
        run_code_graph_pipeline(
            repo_root=str(repo),
            include=["**/*.java"],
            output_root=str(out),
            repo_id=name,
            use_cache=True,
        )
        repos.append(GraphSource(repo_id=name, db_path=str(out / "graph.db"), repo_root=str(repo)))
    return repos


class TestGraphRegistry:
    def test_multi_repo_search(self, dual_graphs):
        reg = GraphRegistry(sources=dual_graphs)
        hits = reg.search("Service", limit=10)
        repo_ids = {h["repo_id"] for h in hits}
        assert "alpha" in repo_ids or "beta" in repo_ids
        assert reg.stats()["repo_count"] == 2
