"""生成代码检测 — 对齐 external/codegraph generated-detection 子集。"""
from __future__ import annotations

import os
import re

# 路径启发式
_GENERATED_PATH_PATTERNS = (
    "/generated/",
    "/gen/",
    "/build/generated/",
    "/target/generated-sources/",
    "/.proto/",
    "/protobuf/",
    "/__generated__/",
)

_GENERATED_SUFFIXES = (
    ".pb.go",
    ".pb.cc",
    ".pb.h",
    ".g.dart",
    ".designer.cs",
    ".generated.cs",
    ".g.cs",
)

# 内容标记（检查文件头部）
_CONTENT_MARKERS = (
    "@Generated",
    "AUTO-GENERATED",
    "AUTOGENERATED",
    "Code generated by",
    "DO NOT EDIT",
    "do not edit",
    "Generated by the protocol buffer",
    "This file is generated",
    "THIS FILE IS GENERATED",
    "generated by protoc",
    "swagger-codegen",
    "openapi-generator",
)


def is_generated_path(rel_path: str) -> bool:
    norm = rel_path.replace(os.sep, "/").lower()
    if any(p in norm for p in _GENERATED_PATH_PATTERNS):
        return True
    lower = rel_path.lower()
    return any(lower.endswith(suf) for suf in _GENERATED_SUFFIXES)


def is_generated_content(content: bytes | str, *, max_scan: int = 4096) -> bool:
    if isinstance(content, bytes):
        try:
            text = content[:max_scan].decode("utf-8", errors="replace")
        except Exception:
            return False
    else:
        text = content[:max_scan]
    for marker in _CONTENT_MARKERS:
        if marker in text:
            return True
    if re.search(r"^//\s*<auto-generated", text, re.MULTILINE | re.IGNORECASE):
        return True
    return False


def classify_file(rel_path: str, content: bytes | None = None) -> str | None:
    """返回 'generated' 或 None。"""
    if is_generated_path(rel_path):
        return "generated"
    if content and is_generated_content(content):
        return "generated"
    return None
